name        : python
version     : 2.7.13
release     : 17
source      :
    - https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz : 35d543986882f78261f97787fd3e06274bfa6df29fac9b4a94f73930ff98f731
license     :
    - Python-2.0
summary     :
    - Python 2.7
    - test: Python 2.7 Test package
    - tkinter: Python 2.7 TKinter package
component   :
    - system.base
    - test: programming.python
    - tkinter: programming.python
builddeps   :
    - pkgconfig(sqlite3)
    - pkgconfig(expat)
    - pkgconfig(libffi)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - db5-devel
devel       : yes
autodep     : no
rundeps     :
    - test: python
    - tkinter:
        - tk
        - tcl
patterns   :
    - /usr/include/python2.7/pyconfig.h
    - test:
        - /usr/lib/python2.7/test
    - tkinter:
        - /usr/lib/python2.7/lib-dynload/_tkinter.so
description : |
    An interactive high-level object-oriented language (version 2.7) Version 2.7 of the high-level, interactive object oriented language, includes an extensive class library with lots of goodies for network programming, system administration, sounds and graphics.
setup      : |
    # Enforce gdbm usage
    sed -e "s/ndbm_libs =.*/ndbm_libs = ['gdbm', 'gdbm_compat']/g" -i setup.py
    # Fix db5
    %patch -p1 < $pkgfiles/Python-2.7.1-berkeley-db-5.3-2.patch
    
    autoreconf -vfi

    # Preserve compat with old Python package in Solus by forcing lib, not lib64
    %configure --prefix=/usr \
               --enable-unicode=ucs4 \
               --with-system-expat \
               --with-system-ffi \
               --with-threads \
               --enable-shared \
               --libdir=/usr/lib \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make
install    : |
    %make_install
