name       : python
version    : 2.7.17
release    : 25
source     :
    - https://www.python.org/ftp/python/2.7.17/Python-2.7.17.tar.xz : 4d43f033cdbd0aa7b7023c81b0e986fd11e653b5248dac9144d508f11812ba41
license    : Python-2.0
component  :
    - system.base
    - test : programming.python
    - tkinter : programming.python
summary    :
    - Python 2.7
    - test : Python 2.7 Test package
    - tkinter : Python 2.7 TKinter package
description: |
    An interactive high-level object-oriented language (version 2.7) Version 2.7 of the high-level, interactive object oriented language, includes an extensive class library with lots of goodies for network programming, system administration, sounds and graphics.
devel      : yes
autodep    : no
optimize   : speed
builddeps  :
    - pkgconfig(expat)
    - pkgconfig(libffi)
    - pkgconfig(sqlite3)
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - bzip2-devel
    - db5-devel
    - gdbm-devel
rundeps    :
    - test : python
    - tkinter :
        - tk
        - tcl
patterns   :
    - /usr/include/python2.7/pyconfig.h
    - test :
        - /usr/lib/python2.7/test
    - tkinter :
        - /usr/lib/python2.7/lib-dynload/_tkinter.so
setup      : |
    # Enforce gdbm usage
    sed -e "s/ndbm_libs =.*/ndbm_libs = ['gdbm', 'gdbm_compat']/g" -i setup.py
    # Fix db5
    %apply_patches

    autoreconf -vfi

    # Preserve compat with old Python package in Solus by forcing lib, not lib64
    %configure --enable-unicode=ucs4 \
               --with-system-expat \
               --with-system-ffi \
               --with-threads \
               --enable-shared \
               --libdir=/usr/lib \
               CFLAGS="$CFLAGS -I/usr/include"
build      : |
    %make profile-opt
install    : |
    %make_install
